// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'center': string;
  'container': string;
  'name': string;
}
declare var cssExports: CssExports;
export = cssExports;
